### ISSUE TITLE
Server example does not run

### ISSUE THREAD

**Issue by rajarshi** [tiarno/mathjax-server#2]
When I run the server example using `node test_server.js` I get the following error traces
```
guhar@HG-01881061-LM8:~/src/node_modules/mathjax-server$ node test_server.js 
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Server listening on port 8003
Error: TypeError: Cannot read property 'replace' of undefined
    at Object.MathJax.Extension.tex2jax.patternQuote (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:121:39)
    at Object.MathJax.Extension.tex2jax.endPattern (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:124:28)
    at Object.MathJax.Extension.tex2jax.createPatterns (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:96:23)
    at Object.MathJax.Extension.tex2jax.PreProcess (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:85:14)
    at Function.CALLBACK.execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:236:26)
    at cb (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:218:59)
    at MathJax.Object.Subclass.Execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:419:36)
    at Function.CALLBACK.execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:236:26)
    at cb (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:218:59)
    at BASE.Object.Subclass.Process (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:488:38)
Error: TypeError: Cannot read property 'replace' of undefined
    at Object.MathJax.Extension.tex2jax.patternQuote (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:121:39)
    at Object.MathJax.Extension.tex2jax.endPattern (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:124:28)
    at Object.MathJax.Extension.tex2jax.createPatterns (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:96:23)
    at Object.MathJax.Extension.tex2jax.PreProcess (file:///Users/guhar/src/node_modules/mathjax/unpacked/extensions/tex2jax.js?rev=2.6.1:85:14)
    at Function.CALLBACK.execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:236:26)
    at cb (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:218:59)
    at MathJax.Object.Subclass.Execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:419:36)
    at Function.CALLBACK.execute (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:236:26)
    at cb (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:218:59)
    at BASE.Object.Subclass.Process (file:///Users/guhar/src/node_modules/mathjax/unpacked/MathJax.js:488:38)
```

I'm running node v5.6.0 and npm 3.6.0

**Comment by tiarno** [comment]
Thanks for the trace. Does that happen when you start the server only or does it happen when you send a request to the server. If the latter, can you show the data you're posting? Thanks.

**Comment by rajarshi** [comment]
It happens as soon as I start the server

**Comment by tiarno** [comment]
I cannot reproduce the problem. Here is what I did (first creating a new empty directory to work in):

    1. downloaded the zip file for mathjax-server
    2. unzipped the master zip file
    3. changed to 'mathjax-server-master'
    4. npm install
    5. node test-server.js
    6. In a new window, go the same directory and give 'node test-client.js'

I get back the SVG output expected. I'm using node v0.12.0 and npm 2.5.1 on FreeBSD.

Here is what npm installs 

    mathjax-node@0.4.0 node_modules/mathjax-node
    ├── yargs@3.32.0 (camelcase@2.1.0, window-size@0.1.4, y18n@3.2.0, decamelize@1.1.2, os-locale@1.4.0, cliui@3.1.0, string-width@1.0.1)
    ├── speech-rule-engine@0.3.1 (xmldom@0.1.22, commander@2.9.0, xpath@0.0.21, xml-mapping@1.7.1)
    ├── jsdom@6.5.1 (acorn-globals@1.0.9, xml-name-validator@2.0.1, xtend@4.0.1, xmlhttprequest@1.8.0, browser-request@0.3.3, cssom@0.3.1, symbol-tree@3.1.4, nwmatcher@1.3.7, tough-cookie@2.2.1, whatwg-url-compat@0.6.5, htmlparser2@3.9.0, parse5@1.5.1, acorn@2.7.0, escodegen@1.8.0, request@2.69.0, cssstyle@0.2.34)
    └── MathJax@2.5.1-mjnode

**Comment by tiarno** [comment]
having troubles on Mac with the same commands, reopening.

**Comment by tiarno** [comment]
I upgraded to node 5.6.0 and npm 3.6.0 and got the same results shown in the issue. I removed the configuration for inline delimiters and it works again. This should have no affect on the server since you pass the math strings in without delimiters anyway. 

Let me know if this latest fix resolves your issue. Thanks.

**Comment by rajarshi** [comment]
Thanks - I forgot to indicate I was on OS X.

The server now runs with no error and the client also runs fine. However the output from the client is
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="0ex" height="0ex" style="vertical-align: 0ex; margin-bottom: 1px; margin-top: 1px;" viewBox="0 -13.9 0 27.9" xmlns="http://www.w3.org/2000/svg" role="math" aria-labelledby="MathJax-SVG-1-Title MathJax-SVG-1-Desc">
<title id="MathJax-SVG-1-Title">Equation</title>
<desc id="MathJax-SVG-1-Desc"></desc>
<defs aria-hidden="true"></defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true"></g>
</svg>
```
As far as I can see there is no representation of the equation in there

**Comment by tiarno** [comment]
you're right, I was just looking to see that svg was created. But the svg was blank. Now I've taken out the displaymath delimiter setup which again should have no effect on the server itself. Now I get a nice svg from the client.

**Comment by rajarshi** [comment]
Works perfectly now. Many thanks!
